spring:
  datasource:
    url: ${DB_URL:jdbc:h2:mem:healthylife}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:}
    driver-class-name: ${DB_DRIVER:org.h2.Driver}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: ${DB_DIALECT:org.hibernate.dialect.H2Dialect}
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: ${SERVER_PORT:8080}

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET:default_jwt_secret_key_for_development}
      expiration: ${JWT_EXPIRATION:86400000}
      refresh-token:
        expiration: ${JWT_REFRESH_EXPIRATION:604800000}

openai:
  api:
    key: ${OPENAI_API_KEY:your_api_key_here}

logging:
  level:
    root: INFO
    com.healthylife: DEBUG
    org.springframework.web: INFO
    org.hibernate: INFO 