server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:healthylife
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

app:
  jwtSecret: your-256-bit-secret-key-here
  jwtExpirationInMs: 86400000 # 24 hours

logging:
  level:
    root: INFO
    com.healthylife: DEBUG 